### ISSUE TITLE
getting file not found exception when i run ant RunTestBed

### ISSUE THREAD

**Issue by anand514** [BOTSlab/PuckSwarm#1]
RunTestbed:
     [java] java.io.FileNotFoundException: C:\Users\u6033361\work\data\srv1\grid
_calib\192.168.0.114\phase2_160x120.csv (The system cannot find the path specifi
ed)
     [java]     at java.io.FileInputStream.open0(Native Method)
     [java]     at java.io.FileInputStream.open(FileInputStream.java:195)
     [java]     at java.io.FileInputStream.<init>(FileInputStream.java:138)
     [java]     at java.util.Scanner.<init>(Scanner.java:611)
     [java]     at sensors.GridCalibration.<init>(GridCalibration.java:62)
     [java]     at sensors.GridCamera.<init>(GridCamera.java:24)
     [java]     at sensors.SimSuite.<init>(SimSuite.java:54)
     [java]     at arena.Robot.<init>(Robot.java:90)
     [java]     at arena.Arena.createRobot(Arena.java:180)
     [java]     at arena.Arena.<init>(Arena.java:105)
     [java]     at arena.PuckSwarmTest.initTest(PuckSwarmTest.java:40)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:227)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:208)
     [java]     at org.jbox2d.testbed.framework.TestbedController.run(TestbedCon
troller.java:304)
     [java]     at java.lang.Thread.run(Thread.java:745)
     [java] javax.imageio.IIOException: Can't read input file!
     [java]     at javax.imageio.ImageIO.read(ImageIO.java:1301)
     [java]     at sensors.GridCalibration.<init>(GridCalibration.java:92)
     [java]     at sensors.GridCamera.<init>(GridCamera.java:24)
     [java]     at sensors.SimSuite.<init>(SimSuite.java:54)
     [java]     at arena.Robot.<init>(Robot.java:90)
     [java]     at arena.Arena.createRobot(Arena.java:180)
     [java]     at arena.Arena.<init>(Arena.java:105)
     [java]     at arena.PuckSwarmTest.initTest(PuckSwarmTest.java:40)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:227)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:208)
     [java]     at org.jbox2d.testbed.framework.TestbedController.run(TestbedCon
troller.java:304)
     [java]     at java.lang.Thread.run(Thread.java:745)
     [java] Exception in thread "Testbed" java.lang.NegativeArraySizeException
     [java]     at sensors.STImage.<init>(STImage.java:18)
     [java]     at localmap.LocalMap.<init>(LocalMap.java:114)
     [java]     at sensors.SimSuite.<init>(SimSuite.java:57)
     [java]     at arena.Robot.<init>(Robot.java:90)
     [java]     at arena.Arena.createRobot(Arena.java:180)
     [java]     at arena.Arena.<init>(Arena.java:105)
     [java]     at arena.PuckSwarmTest.initTest(PuckSwarmTest.java:40)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:227)
     [java]     at org.jbox2d.testbed.framework.TestbedTest.init(TestbedTest.jav
a:208)
     [java]     at org.jbox2d.testbed.framework.TestbedController.run(TestbedCon
troller.java:304)
     [java]     at java.lang.Thread.run(Thread.java:745)

**Comment by avardy** [comment]
I've pushed an update that should help.  There were some data files not incorporated into the repository.  I have placed them there now.

Hope this helps!
Andrew
